'use client';
import { useState } from 'react';
import { AppShell, Badge, Button, Card, Field, Row } from './ui/AppShell';
import { useEventStore } from './EventStore';
import { blankSubmission, id } from '@/lib/defaults';
import { cleanUrl, fileToDataUrl } from '@/lib/utils';
import { supabase } from '@/lib/supabaseClient';
export default function ArtistBookingForm(){const {createArtist,usingLocal}=useEventStore();const [form,setForm]=useState(blankSubmission());const [msg,setMsg]=useState('');const set=(k:string,v:any)=>setForm(f=>({...f,[k]:v}));const setLink=(k:string,v:string)=>setForm(f=>({...f,links:{...f.links,[k]:cleanUrl(v)}}));async function image(file?:File){if(!file)return;try{if(supabase){const path=`${id()}-${file.name}`;const up=await supabase.storage.from('artist-images').upload(path,file,{upsert:true});if(up.error)throw up.error;const {data}=supabase.storage.from('artist-images').getPublicUrl(path);set('image_url',data.publicUrl)}else set('image_url',await fileToDataUrl(file));}catch(e:any){set('image_url',await fileToDataUrl(file));setMsg(`Image stored locally. Upload failed: ${e?.message||''}`)}}
async function submit(e:React.FormEvent){e.preventDefault();try{await createArtist({...form, id:id(), status:'new', preferred_fee:Number(form.preferred_fee)||0, links:Object.fromEntries(Object.entries(form.links).map(([k,v])=>[k,cleanUrl(String(v||''))]))});setForm(blankSubmission());setMsg('Submission received. Thank you.')}catch(err:any){setMsg(`Submission failed: ${err?.message||'Unknown error'}`)}}
const input=(label:string,key:string,type='text')=><Field label={label}><input required={['artist_name','email'].includes(key)} type={type} value={(form as any)[key]??''} onChange={e=>set(key,type==='number'?Number(e.target.value):e.target.value)}/></Field>;
return <AppShell title="Artist Booking" actions={<Badge tone={usingLocal?'warn':'ok'}>{usingLocal?'Local':'Live'}</Badge>}><form onSubmit={submit} className="space-y-5"><Card><p className="text-sm text-zinc-500">Public submission form</p><h2 className="mt-2 text-4xl font-semibold leading-none tracking-[-.075em]">Apply to play</h2><p className="mt-3 text-sm text-zinc-500">Send artist details, links, image, availability, technical needs and preferred fee.</p>{msg&&<p className="mt-4 rounded-2xl border border-white/10 bg-white/[.04] p-3 text-sm">{msg}</p>}</Card><Card className="space-y-3"><Row>{input('Artist name','artist_name')}{input('Contact name','contact_name')}</Row><Row>{input('Email','email','email')}{input('Phone','phone','tel')}</Row>{input('Genre','genre')}<Field label="Description"><textarea value={form.description} onChange={e=>set('description',e.target.value)}/></Field><Field label="Artist image"><input type="file" accept="image/*" onChange={e=>image(e.target.files?.[0])}/>{form.image_url&&<img src={form.image_url} className="mt-3 h-44 w-full rounded-3xl object-cover" alt="Artist preview"/>}</Field></Card><Card className="space-y-3"><h3 className="text-xl font-semibold tracking-[-.04em]">Links</h3>{['instagram','spotify','soundcloud','youtube','website'].map(k=><Field key={k} label={k}><input value={(form.links as any)[k]||''} onChange={e=>setLink(k,e.target.value)} /></Field>)}</Card><Card className="space-y-3"><h3 className="text-xl font-semibold tracking-[-.04em]">Availability and needs</h3>{input('Availability date/text','availability')}<Row>{input('Start time','availability_start_time','time')}{input('End time','availability_end_time','time')}</Row>{input('Preferred fee','preferred_fee','number')}<Field label="Technical needs"><textarea value={form.technical_needs} onChange={e=>set('technical_needs',e.target.value)}/></Field><Field label="Hospitality needs"><textarea value={form.hospitality_needs} onChange={e=>set('hospitality_needs',e.target.value)}/></Field><Field label="Notes"><textarea value={form.notes} onChange={e=>set('notes',e.target.value)}/></Field><Button type="submit" className="w-full">Submit artist</Button></Card></form></AppShell>}
