'use client';
import Link from 'next/link';
import { AppShell, Badge, Button, Card, Stat } from './ui/AppShell';
import { useEventStore } from './EventStore';
import { eventTotals } from '@/lib/calculations';
const modules=[
 ['/event-planner','Event Planner','Forecast tickets, costs, staff, bar and venue terms.','Active'],
 ['/artist-booking','Artist Booking','Public artist submission form with image upload.','Public'],
 ['/artists','Artist Management','Review submissions and connect artists to events.','Active'],
 ['/calendar','Calendar / Schedule','Review upcoming events, timings and warnings.','Active'],
 ['/bar-planner','Bar Planner','Plan products, staff, menu and bar profit.','Active'],
 ['/project-management','Project Management','Manage projects, tasks, owners and due dates.','Active']
];
const future=['Staff planner','Contracts','Supplier list','Budget reports'];
export default function Dashboard(){const {events,artists,tasks,alert,usingLocal}=useEventStore();const upcoming=events.filter(e=>e.meta.date).sort((a,b)=>a.meta.date.localeCompare(b.meta.date))[0];const totals=upcoming?eventTotals(upcoming):null;return <AppShell title="Operations" actions={<Badge tone={usingLocal?'warn':'ok'}>{usingLocal?'Local':'Live'}</Badge>}><div className="space-y-5"><Card className="overflow-hidden"><div className="flex items-start justify-between"><div><p className="text-sm text-zinc-500">Connected mobile workspace</p><h2 className="mt-2 text-4xl font-semibold leading-none tracking-[-.075em]">Event Operations System</h2></div><div className="rounded-full bg-white p-3 text-black">＋</div></div><div className="mt-5 grid grid-cols-3 gap-2"><Stat label="Events" value={events.length}/><Stat label="Artists" value={artists.length}/><Stat label="Open tasks" value={tasks.filter(t=>!['done','archived'].includes(t.status)).length}/></div>{alert&&<p className="mt-4 rounded-2xl border border-amber-300/20 bg-amber-300/10 p-3 text-sm text-amber-100">{alert}</p>}</Card>{upcoming&&<Card><div className="flex items-center justify-between"><div><p className="text-xs uppercase tracking-[.2em] text-zinc-500">Next review</p><h3 className="mt-2 text-2xl font-semibold tracking-[-.05em]">{upcoming.meta.name}</h3><p className="text-sm text-zinc-500">{upcoming.meta.date} {upcoming.meta.time} · {upcoming.meta.location||'No location'}</p></div><Badge>{upcoming.meta.status}</Badge></div><div className="mt-4 grid grid-cols-2 gap-3"><Stat label="Projected" value={totals?new Intl.NumberFormat('da-DK',{style:'currency',currency:'DKK',maximumFractionDigits:0}).format(totals.profit):'—'}/><Stat label="Warnings" value={[!upcoming.meta.date,!upcoming.meta.time,!upcoming.meta.location,...upcoming.artists.map(a=>!a.startTime||!a.fee)].filter(Boolean).length}/></div><Link href="/calendar"><Button className="mt-4 w-full">Open readiness view</Button></Link></Card>}<div className="space-y-3"><h2 className="text-3xl font-semibold tracking-[-.06em]">Modules</h2>{modules.map(([href,name,desc,status])=><Link key={href} href={href} className="block"><Card className="transition active:scale-[.99]"><div className="flex items-center justify-between gap-3"><div><h3 className="text-xl font-semibold tracking-[-.04em]">{name}</h3><p className="mt-1 text-sm text-zinc-500">{desc}</p></div><div className="text-right"><Badge tone={status==='Public'?'warn':'ok'}>{status}</Badge><div className="mt-3 text-2xl text-zinc-500">›</div></div></div></Card></Link>)}</div><Card><h3 className="text-xl font-semibold tracking-[-.04em]">Future modules</h3><div className="mt-3 flex flex-wrap gap-2">{future.map(x=><Badge key={x}>{x}</Badge>)}</div></Card></div></AppShell>}
