'use client';
import { createContext, ReactNode, useContext, useEffect, useMemo, useState } from 'react';
import { ArtistSubmission, PlannerEvent, Project, Task } from '@/lib/types';
import { blankProject, blankSubmission, blankTask, eventFromTemplate, hydrateEvent, now } from '@/lib/defaults';
import { supabase, supabaseReady } from '@/lib/supabaseClient';

type Store = { ownerKey:string; setOwnerKey:(v:string)=>void; events:PlannerEvent[]; currentId:string; current?:PlannerEvent; setCurrentId:(id:string)=>void; saveEvent:(e:PlannerEvent)=>Promise<void>; createEvent:(template:string)=>Promise<PlannerEvent>; duplicateEvent:(id:string)=>Promise<void>; deleteEvent:(id:string)=>Promise<void>; artists:ArtistSubmission[]; saveArtist:(a:ArtistSubmission)=>Promise<void>; createArtist:(a:ArtistSubmission)=>Promise<void>; projects:Project[]; tasks:Task[]; saveProject:(p:Project)=>Promise<void>; deleteProject:(id:string)=>Promise<void>; saveTask:(t:Task)=>Promise<void>; deleteTask:(id:string)=>Promise<void>; refresh:()=>Promise<void>; alert:string; usingLocal:boolean };
const C=createContext<Store|null>(null);
const LS='eos-v1';
const readLocal=()=>{if(typeof window==='undefined')return null;try{return JSON.parse(localStorage.getItem(LS)||'{}')}catch{return {}}};
const stripStoredFiles=(event:PlannerEvent):PlannerEvent=>({...event,files:(event.files||[]).map(file=>({...file,dataUrl:file.dataUrl?.startsWith('data:')?'':file.dataUrl}))});
const safeLocalData=(data:any)=>({...data,events:(data.events||[]).map(stripStoredFiles)});
const writeLocal=(data:any)=>{if(typeof window!=='undefined')try{localStorage.setItem(LS,JSON.stringify(safeLocalData(data)))}catch{localStorage.setItem(LS,JSON.stringify(safeLocalData({...data,events:[]})))}};
const dbToEvent=(r:any)=>hydrateEvent({id:r.id,...(r.payload||{}),updatedAt:r.updated_at});
const eventToPayload=(e:PlannerEvent)=>{const {id,updatedAt,...payload}=stripStoredFiles(e); return payload};
export function EventStoreProvider({children}:{children:ReactNode}){const local=readLocal()||{};const [ownerKey,setOwnerKeyState]=useState(local.ownerKey||'default-workspace');const [events,setEvents]=useState<PlannerEvent[]>((local.events||[]).map(hydrateEvent));const [artists,setArtists]=useState<ArtistSubmission[]>(local.artists||[]);const [projects,setProjects]=useState<Project[]>(local.projects||[]);const [tasks,setTasks]=useState<Task[]>(local.tasks||[]);const [currentId,setCurrentId]=useState(local.currentId||'');const [alert,setAlert]=useState('');const [usingLocal,setUsingLocal]=useState(!supabaseReady);
useEffect(()=>{writeLocal({ownerKey,events,artists,projects,tasks,currentId})},[ownerKey,events,artists,projects,tasks,currentId]);
const refresh=async()=>{if(!supabase){setUsingLocal(true);return}try{const [ev,ar,pr,ta]=await Promise.all([supabase.from('event_plans').select('*').eq('owner_key',ownerKey).order('event_date'),supabase.from('artist_submissions').select('*').order('created_at',{ascending:false}),supabase.from('project_management_projects').select('*').order('updated_at',{ascending:false}),supabase.from('project_management_tasks').select('*').order('updated_at',{ascending:false})]);if(ev.error||ar.error||pr.error||ta.error)throw ev.error||ar.error||pr.error||ta.error;setEvents((ev.data||[]).map(dbToEvent));setArtists((ar.data||[]).map((a:any)=>({...a,links:typeof a.links==='string'?JSON.parse(a.links||'{}'):a.links||{}})));setProjects(pr.data||[]);setTasks((ta.data||[]).map((t:any)=>({...t,checklist:t.checklist||[],image_urls:t.image_urls||[]})));setUsingLocal(false);setAlert('Synced with Supabase')}catch(e:any){setUsingLocal(true);setAlert(`Supabase unavailable. Local mode active. ${e?.message||''}`)}};
useEffect(()=>{refresh()},[ownerKey]);
const setOwnerKey=(v:string)=>{setOwnerKeyState(v||'default-workspace')};
const saveEvent=async(e:PlannerEvent)=>{const next={...hydrateEvent(e),updatedAt:now()};setEvents(prev=>[next,...prev.filter(x=>x.id!==next.id)]);setCurrentId(next.id);if(supabase)try{const {error}=await supabase.from('event_plans').upsert({id:next.id,owner_key:ownerKey,name:next.meta.name,event_date:next.meta.date||null,payload:eventToPayload(next),updated_at:next.updatedAt});if(error)throw error;setUsingLocal(false);setAlert('Event saved')}catch(err:any){setUsingLocal(true);setAlert(`Saved locally. Supabase save failed: ${err?.message||''}`)}};
const createEvent=async(template:string)=>{const e=eventFromTemplate(template);await saveEvent(e);return e};
const duplicateEvent=async(id:string)=>{const e=events.find(x=>x.id===id);if(e)await saveEvent(hydrateEvent({...e,id:crypto.randomUUID(),meta:{...e.meta,name:`${e.meta.name} copy`},updatedAt:now()}))};
const deleteEvent=async(id:string)=>{setEvents(p=>p.filter(e=>e.id!==id)); if(currentId===id)setCurrentId(''); if(supabase)await supabase.from('event_plans').delete().eq('id',id)};
const saveArtist=async(a:ArtistSubmission)=>{const next={...blankSubmission(),...a,updated_at:now()};setArtists(p=>[next,...p.filter(x=>x.id!==next.id)]); if(supabase)try{const {error}=await supabase.from('artist_submissions').upsert(next);if(error)throw error;setAlert('Artist saved')}catch(e:any){setUsingLocal(true);setAlert(`Artist saved locally: ${e?.message||''}`)}};
const createArtist=saveArtist;
const saveProject=async(p:Project)=>{const next={...blankProject(),...p,updated_at:now()};setProjects(a=>[next,...a.filter(x=>x.id!==next.id)]);if(supabase)await supabase.from('project_management_projects').upsert(next)};
const deleteProject=async(id:string)=>{setProjects(p=>p.filter(x=>x.id!==id));if(supabase)await supabase.from('project_management_projects').delete().eq('id',id)};
const saveTask=async(t:Task)=>{const next={...blankTask(),...t,updated_at:now()};setTasks(a=>[next,...a.filter(x=>x.id!==next.id)]);if(supabase)await supabase.from('project_management_tasks').upsert(next)};
const deleteTask=async(id:string)=>{setTasks(p=>p.filter(x=>x.id!==id));if(supabase)await supabase.from('project_management_tasks').delete().eq('id',id)};
const current=events.find(e=>e.id===currentId)||events[0];
const value=useMemo(()=>({ownerKey,setOwnerKey,events,currentId:current?.id||'',current,setCurrentId,saveEvent,createEvent,duplicateEvent,deleteEvent,artists,saveArtist,createArtist,projects,tasks,saveProject,deleteProject,saveTask,deleteTask,refresh,alert,usingLocal}),[ownerKey,events,currentId,artists,projects,tasks,alert,usingLocal]);
return <C.Provider value={value}>{children}</C.Provider>}
export const useEventStore=()=>{const v=useContext(C);if(!v)throw new Error('Store missing');return v};
