'use client';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { ReactNode } from 'react';
import { cx } from '@/lib/utils';
const nav=[['/','Main','⌁'],['/event-planner','Planner','◴'],['/artists','Artists','◎'],['/calendar','Calendar','▦'],['/project-management','Tasks','⚙']];
export function AppShell({children}:{title?:string;children:ReactNode;actions?:ReactNode}){const path=useRouter().pathname;return <main className="mx-auto min-h-screen max-w-[430px] bg-[#08090b] safe"><section className="px-5 pb-44 pt-[calc(env(safe-area-inset-top)+18px)]">{children}</section><nav className="fixed bottom-[calc(env(safe-area-inset-bottom)+18px)] left-1/2 z-30 w-[calc(100%-28px)] max-w-[390px] -translate-x-1/2 rounded-[32px] border border-white/10 bg-[#151619]/86 px-2 py-2 shadow-2xl shadow-black/50 backdrop-blur-2xl"><div className="grid grid-cols-5 gap-1">{nav.map(([href,label,ico])=><Link key={href} href={href} className={cx('rounded-[24px] px-1 py-2 text-center text-[11px] text-zinc-500 transition active:scale-[.97]',path===href&&'bg-white/[.085] text-white')}><div className={cx('mx-auto mb-1 grid h-7 w-7 place-items-center rounded-full border border-white/10 text-base',path===href&&'border-white/20 bg-white/[.05]')}>{ico}</div>{label}</Link>)}</div></nav></main>}
export function Button({children,onClick,kind='primary',type='button',className='',disabled=false}:{children:ReactNode;onClick?:()=>void;kind?:'primary'|'ghost'|'danger'|'soft';type?:'button'|'submit';className?:string;disabled?:boolean}){return <button type={type} disabled={disabled} onClick={onClick} className={cx('focus-ring rounded-2xl px-4 py-3 text-sm font-semibold transition active:scale-[.98] disabled:opacity-40',kind==='primary'&&'bg-white text-black',kind==='ghost'&&'border border-white/10 bg-white/[.03] text-white',kind==='danger'&&'bg-red-400/15 text-red-200 border border-red-300/20',kind==='soft'&&'bg-white/[.08] text-white',className)}>{children}</button>}
export function Card({children,className=''}:{children:ReactNode;className?:string}){return <div className={cx('glass rounded-[28px] p-4',className)}>{children}</div>}
export function Stat({label,value,sub,className=''}:{label:string;value:string|number;sub?:string;className?:string}){return <div className={cx('min-w-0 overflow-hidden rounded-[20px] bg-white/[.055] p-3',className)}><div className="truncate text-[11px] text-zinc-500">{label}</div><div className="mt-2 truncate text-xl font-semibold leading-none tracking-[-.04em]">{value}</div>{sub&&<div className="mt-1 truncate text-xs text-zinc-500">{sub}</div>}</div>}
export function Badge({children,tone='neutral'}:{children:ReactNode;tone?:'neutral'|'ok'|'warn'|'bad'}){return <span className={cx('pill inline-flex items-center gap-1 border px-2.5 py-1 text-xs',tone==='neutral'&&'border-white/10 bg-white/[.04] text-zinc-300',tone==='ok'&&'border-emerald-300/20 bg-emerald-300/10 text-emerald-200',tone==='warn'&&'border-amber-300/20 bg-amber-300/10 text-amber-200',tone==='bad'&&'border-red-300/20 bg-red-300/10 text-red-200')}>{children}</span>}
export function Section({title,children,openDefault=false,right}:{title:string;children:ReactNode;openDefault?:boolean;right?:ReactNode}){return <details open={openDefault} className="group rounded-[26px] border border-white/10 bg-white/[.035] p-1"><summary className="flex cursor-pointer list-none items-center justify-between gap-2 px-4 py-3"><span className="font-semibold tracking-[-.03em]">{title}</span><span className="flex items-center gap-2 text-xs text-zinc-500">{right}<span className="text-lg group-open:rotate-180">⌄</span></span></summary><div className="space-y-3 px-3 pb-3">{children}</div></details>}
export function Field({label,children}:{label:string;children:ReactNode}){return <div className="min-w-0"><label>{label}</label>{children}</div>}
export function Row({children}:{children:ReactNode}){return <div className="grid min-w-0 grid-cols-1 gap-3">{children}</div>}
