'use client';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { ReactNode } from 'react';
import { cx } from '@/lib/utils';
const nav=[['/','Main','⌁'],['/event-planner','Planner','◴'],['/artists','Artists','◎'],['/calendar','Calendar','▦'],['/project-management','Tasks','⚙']];
export function AppShell({title,children,actions}:{title:string;children:ReactNode;actions?:ReactNode}){const path=usePathname();return <main className="mx-auto min-h-screen max-w-[430px] bg-[#08090b] safe"><header className="sticky top-0 z-20 border-b border-white/5 bg-[#08090b]/88 px-5 pb-3 pt-[calc(env(safe-area-inset-top)+14px)] backdrop-blur-xl"><div className="flex items-center justify-between gap-3"><Link href="/" className="grid h-10 w-10 place-items-center rounded-full border border-white/10 bg-white/[.04] text-xl">≡</Link><h1 className="truncate text-[28px] font-semibold tracking-[-.06em]">{title}</h1><div className="flex min-w-10 items-center justify-end gap-2">{actions}</div></div></header><section className="px-5 py-5">{children}</section><nav className="fixed bottom-0 left-1/2 z-30 w-full max-w-[430px] -translate-x-1/2 border-t border-white/10 bg-[#090a0b]/92 px-3 pb-[calc(env(safe-area-inset-bottom)+10px)] pt-2 backdrop-blur-xl"><div className="grid grid-cols-5 gap-1">{nav.map(([href,label,ico])=><Link key={href} href={href} className={cx('rounded-2xl px-1 py-2 text-center text-[11px] text-zinc-500',path===href&&'bg-white/[.06] text-white')}><div className="mx-auto mb-1 grid h-7 w-7 place-items-center rounded-full border border-white/10 text-base">{ico}</div>{label}</Link>)}</div></nav></main>}
export function Button({children,onClick,kind='primary',type='button',className='',disabled=false}:{children:ReactNode;onClick?:()=>void;kind?:'primary'|'ghost'|'danger'|'soft';type?:'button'|'submit';className?:string;disabled?:boolean}){return <button type={type} disabled={disabled} onClick={onClick} className={cx('focus-ring rounded-2xl px-4 py-3 text-sm font-semibold transition active:scale-[.98] disabled:opacity-40',kind==='primary'&&'bg-white text-black',kind==='ghost'&&'border border-white/10 bg-white/[.03] text-white',kind==='danger'&&'bg-red-400/15 text-red-200 border border-red-300/20',kind==='soft'&&'bg-white/[.08] text-white',className)}>{children}</button>}
export function Card({children,className=''}:{children:ReactNode;className?:string}){return <div className={cx('glass rounded-[28px] p-4',className)}>{children}</div>}
export function Stat({label,value,sub}:{label:string;value:string|number;sub?:string}){return <div className="min-w-[132px] rounded-[22px] bg-white/[.055] p-4"><div className="text-xs text-zinc-500">{label}</div><div className="mt-2 text-xl font-semibold tracking-[-.04em]">{value}</div>{sub&&<div className="mt-1 text-xs text-zinc-500">{sub}</div>}</div>}
export function Badge({children,tone='neutral'}:{children:ReactNode;tone?:'neutral'|'ok'|'warn'|'bad'}){return <span className={cx('pill inline-flex items-center gap-1 border px-2.5 py-1 text-xs',tone==='neutral'&&'border-white/10 bg-white/[.04] text-zinc-300',tone==='ok'&&'border-emerald-300/20 bg-emerald-300/10 text-emerald-200',tone==='warn'&&'border-amber-300/20 bg-amber-300/10 text-amber-200',tone==='bad'&&'border-red-300/20 bg-red-300/10 text-red-200')}>{children}</span>}
export function Section({title,children,openDefault=false,right}:{title:string;children:ReactNode;openDefault?:boolean;right?:ReactNode}){return <details open={openDefault} className="group rounded-[26px] border border-white/10 bg-white/[.035] p-1"><summary className="flex cursor-pointer list-none items-center justify-between gap-2 px-4 py-3"><span className="font-semibold tracking-[-.03em]">{title}</span><span className="flex items-center gap-2 text-xs text-zinc-500">{right}<span className="text-lg group-open:rotate-180">⌄</span></span></summary><div className="space-y-3 px-3 pb-3">{children}</div></details>}
export function Field({label,children}:{label:string;children:ReactNode}){return <div><label>{label}</label>{children}</div>}
export function Row({children}:{children:ReactNode}){return <div className="grid grid-cols-2 gap-3">{children}</div>}
