import { PlannerEvent, MoneyLine, StaffLine, BarProduct, BarStaffLine, Scenario } from './types';
export const num=(v:any)=>Number.isFinite(Number(v))?Number(v):0;
export const dkk=(v:any)=>new Intl.NumberFormat('da-DK',{style:'currency',currency:'DKK',maximumFractionDigits:0}).format(num(v));
export const pct=(v:any)=>`${Math.round(num(v)*10)/10}%`;
export function ticketTotals(e:PlannerEvent){const sold=e.tickets.reduce((s,t)=>s+num(t.sold),0);const cap=e.tickets.reduce((s,t)=>s+num(t.capacity),0);const rev=e.tickets.reduce((s,t)=>s+num(t.sold)*num(t.price),0);return{sold,cap,rev,fill:cap?sold/cap*100:0,avg:sold?rev/sold:0};}
export function lineTotal(l:MoneyLine,e:PlannerEvent){const t=ticketTotals(e);if(l.mode==='perTicketHolder')return num(l.amount)*t.sold*num(l.quantity);if(l.mode==='percentageOfTickets')return t.rev*(num(l.amount)/100);return num(l.amount)*num(l.quantity)}
export function staffTotal(s:StaffLine){const base=num(s.people)*num(s.hours)*num(s.hourlyWage);return base+(base*num(s.extraPercent)/100)}
export function barTotals(e:PlannerEvent){const t=ticketTotals(e);const guests=e.bar.useTicketGuests?t.sold:num(e.bar.customGuests);const revenue=e.bar.enabled?guests*num(e.bar.spendPerGuest):0;const stockCost=revenue*num(e.bar.costPercent)/100;return{guests,revenue,stockCost,profit:revenue-stockCost};}
export function eventTotals(e:PlannerEvent){const t=ticketTotals(e);const extraIncome=e.lines.filter(l=>l.kind==='income').reduce((s,l)=>s+lineTotal(l,e),0);const expenses=e.lines.filter(l=>l.kind==='expense').reduce((s,l)=>s+lineTotal(l,e),0);const staffCost=e.staff.reduce((s,l)=>s+staffTotal(l),0);const artistCost=e.artists.reduce((s,a)=>s+num(a.fee),0);const bar=barTotals(e);const totalIncome=t.rev+extraIncome+bar.revenue;const totalCosts=expenses+staffCost+artistCost+bar.stockCost;const profit=totalIncome-totalCosts;const profitPerGuest=t.sold?profit/t.sold:0;const margin=totalIncome?profit/totalIncome*100:0;const breakEvenGuests=t.avg+num(e.bar.spendPerGuest)*(1-num(e.bar.costPercent)/100)>0?Math.ceil((expenses+staffCost+artistCost)/(t.avg+num(e.bar.spendPerGuest)*(1-num(e.bar.costPercent)/100))):0;let organizer=profit,venue=0;if(e.termsPlan.enabled){const organizerTickets=t.rev*num(e.termsPlan.organizerTicketShare)/100;const organizerBar=bar.profit*num(e.termsPlan.organizerBarProfitShare)/100;organizer=organizerTickets+organizerBar+extraIncome-expenses-staffCost-artistCost-num(e.termsPlan.flatVenueHire);venue=(t.rev-organizerTickets)+(bar.profit-organizerBar)+num(e.termsPlan.flatVenueHire);if(num(e.termsPlan.minimumVenueGuarantee)>venue){organizer-=num(e.termsPlan.minimumVenueGuarantee)-venue;venue=num(e.termsPlan.minimumVenueGuarantee)}}return{tickets:t,extraIncome,expenses,staffCost,artistCost,bar,totalIncome,totalCosts,profit,profitPerGuest,margin,breakEvenGuests,organizer,venue};}
export function scenarioTotal(s:Scenario, fixedCost=0){const tickets=num(s.ticketsSold)*num(s.averageTicketPrice);const bar=num(s.ticketsSold)*num(s.barSpendPerGuest);return{revenue:tickets+bar,costs:fixedCost+num(s.extraExpenses),profit:tickets+bar-fixedCost-num(s.extraExpenses)}}
export function barProductTotal(p:BarProduct){const revenue=num(p.sellPrice)*num(p.expectedQty);const stockCost=num(p.buyPrice)*num(p.expectedQty);const profit=revenue-stockCost;return{revenue,stockCost,profit,margin:revenue?profit/revenue*100:0};}
export function hoursBetween(start:string,end:string){if(!start||!end)return 0;const [sh,sm]=start.split(':').map(num),[eh,em]=end.split(':').map(num);let a=sh+(sm||0)/60,b=eh+(em||0)/60;if(b<a)b+=24;return Math.max(0,b-a)}
export function barStaffCost(s:BarStaffLine){return num(s.staffCount)*hoursBetween(s.startTime,s.endTime)*num(s.hourlyWage)}
